### ISSUE TITLE
Plugin is not compatible with latest IntelliJ version 2019.1

### ISSUE THREAD

**Issue by milowg** [alivesubstance/branch-manager#11]
When I upgraded to the latest IntelliJ this plugin no longer works.

**Comment by alivesubstance** [comment]
Thank for info. Will fix it soon.

**Comment by milowg** [comment]
It turned out to be an easy fix. I've made the change and created a PR:
https://github.com/alivesubstance/branch-manager/pull/12

**Comment by alivesubstance** [comment]
Thanks for PR. New version 1.0.3 with fix is available in plugin repository
