### ISSUE TITLE
IDEA already has that feature for multimodiule projects. Why do we need this plugin?

### ISSUE THREAD

**Issue by kool79** [alivesubstance/branch-manager#13]
https://blog.jetbrains.com/idea/2012/08/git-branches-for-multi-root-projects/

In the Settings/Preferences dialog (Ctrl+Alt+S) select Version Control | Git.
Select the Execute branch operations on all roots option.

**Comment by alivesubstance** [comment]
I know about it. But there is one disadvantage. You can't choose exact repositories to create branch. Let's imagine you have 15 repositories(one per maven project) loaded into IDEA and only 5 of them have changes in active change list. 
You can use native IDEA feature and create the same branch for all roots. It creates branch in each repo but you need only 5, cause only 5 repos have changes. With help of plugin you can point to exact repos to create branch in. Moreover plugin analyze changes in active changelist and preselect repos when open VCS | Branch Manager | Checkout branch UI.
Second plugin feature is to remove untracked(missing on remote) local branches. This feature is absent in IDEA.
