### ISSUE TITLE
Add compatibility for 2021.1

### ISSUE THREAD

**Issue by huehnerlady** [alivesubstance/branch-manager#24]
Currently this plugin is not usable for 2021.1, please update
![image](https://user-images.githubusercontent.com/12533979/114554528-1d2d3a80-9c67-11eb-8b2e-e76020a8b107.png)

**Comment by alivesubstance** [comment]
Ok, will fix soon

**Comment by alivesubstance** [comment]
New version has been submitted to jetbrains plugins repo

**Comment by huehnerlady** [comment]
works, thanks for the very quick reaction 👍🏻

**Comment by alivesubstance** [comment]
not at all
