### ISSUE TITLE
support intellij 2021.2.2

### ISSUE THREAD

**Issue by huehnerlady** [alivesubstance/branch-manager#26]
I try to install the plugin on 2021.2.2, but I get the error that the plugin is not compatible with my build, it needs an older version.

Please add support of latest intellij version

Intellij
IntelliJ IDEA 2021.2.2 (Ultimate Edition)
Build #IU-212.5284.40, built on September 14, 2021
Runtime version: 11.0.12+7-b1504.28 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 750M
Cores: 16
Non-Bundled Plugins: net.ashald.envfile (3.2.2), com.nbadal.ktlint (0.8.1), kotest-plugin-intellij (1.1.37-IC-2021.1)
Kotlin: 212-1.5.10-release-IJ5284.40

**Comment by huehnerlady** [comment]
It was my fault, sorry

**Comment by alivesubstance** [comment]
you are welcome )
