### ISSUE TITLE
Compatibility to IntelliJ IDEA 2022.1.1

### ISSUE THREAD

**Issue by Faldrian** [alivesubstance/branch-manager#28]
Hello!

I would really like this to work again in IntelliJ IDEA 2022.1.1 :) It helps a lot to keep my local branches to a minimum and I miss it a lot. :)

If you no longer maintain this, please send a message, maybe I have to take my time to get into plugin development and fix it myself... :-/

**Comment by alivesubstance** [comment]
Hi. I will release new version this weekend. If you wan you can contribute )

**Comment by alivesubstance** [comment]
Sooner or later the new version has been uploaded today
