### ISSUE TITLE
Support for WebStorm / IntelliJ / GoLand 2022.2.X

### ISSUE THREAD

**Issue by anthonybriand** [alivesubstance/branch-manager#29]
Hello!

I have updated my JetBrains tools and the plugin is not compatible anymore with the versions 2022.2.1 and 2022.2.2 :/
Have you planned to update the plugin to support these versions ?

Thanks a lot for your work!

**Comment by alivesubstance** [comment]
hi. will update it soon.

**Comment by alivesubstance** [comment]
uploaded new version today. should be available soon
