### ISSUE TITLE
Support Intellij 2023.1.x

### ISSUE THREAD

**Issue by huehnerlady** [alivesubstance/branch-manager#30]
Hi,

I updated intellij and now this plugin is not compatible anymore. 

Could you please update the plugin so it is usable again? :)

**Comment by alivesubstance** [comment]
hi, why not )

**Comment by huehnerlady** [comment]
Hi, any update on this? Now there is 2023.1 out so maybe that can be supported now as well? :)

**Comment by alivesubstance** [comment]
yep) It's so boring increase necessary versions for every new IDEA version

**Comment by huehnerlady** [comment]
If you have an example I am happy to give it a try to create a pull request. Only problem I have is there is no documentation on how your contribution process works :)

**Comment by alivesubstance** [comment]
I've uploaded new version today. You are right here is no documentation at all :) I'm too lazy to write it %)
